<?php

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use Liberu\Foundation\Organizations\Models\Team;
use Liberu\Genealogy\Dna\Actions\CreateDnaGroup;
use Liberu\Genealogy\Dna\Actions\CreateDnaKit;
use Liberu\Genealogy\Dna\Actions\CreateDnaMatch;
use Liberu\Genealogy\Dna\Actions\CreateDnaNote;
use Liberu\Genealogy\Dna\Actions\CreateDnaProvider;
use Liberu\Genealogy\Dna\Actions\CreateDnaRelationship;
use Liberu\Genealogy\Dna\Actions\CreateDnaSegment;
use Liberu\Genealogy\Dna\Actions\DeleteDnaGroup;
use Liberu\Genealogy\Dna\Actions\DeleteDnaKit;
use Liberu\Genealogy\Dna\Actions\DeleteDnaMatch;
use Liberu\Genealogy\Dna\Actions\DeleteDnaNote;
use Liberu\Genealogy\Dna\Actions\DeleteDnaProvider;
use Liberu\Genealogy\Dna\Actions\DeleteDnaRelationship;
use Liberu\Genealogy\Dna\Actions\DeleteDnaSegment;
use Liberu\Genealogy\Dna\Actions\GrantDnaConsent;
use Liberu\Genealogy\Dna\Actions\ImportDnaKit;
use Liberu\Genealogy\Dna\Actions\PersistDnaComparison;
use Liberu\Genealogy\Dna\Actions\RevokeDnaKit;
use Liberu\Genealogy\Dna\Actions\UpdateDnaGroup;
use Liberu\Genealogy\Dna\Actions\UpdateDnaKit;
use Liberu\Genealogy\Dna\Actions\UpdateDnaMatch;
use Liberu\Genealogy\Dna\Actions\UpdateDnaProvider;
use Liberu\Genealogy\Dna\Actions\UpdateDnaSegment;
use Liberu\Genealogy\Dna\Events\DnaMatchesPersisted;
use Liberu\Genealogy\Dna\Filament\Resources\DnaProviderResource;
use Liberu\Genealogy\Dna\Models\DnaConsent;
use Liberu\Genealogy\Dna\Models\DnaGroup;
use Liberu\Genealogy\Dna\Models\DnaKit;
use Liberu\Genealogy\Dna\Models\DnaMatch;
use Liberu\Genealogy\Dna\Models\DnaNote;
use Liberu\Genealogy\Dna\Models\DnaProvider;
use Liberu\Genealogy\Dna\Models\DnaRelationship;
use Liberu\Genealogy\Dna\Models\DnaSegment;
use Liberu\Genealogy\Dna\Services\DnaFileVault;
use Liberu\Genealogy\GenealogyCore\TeamContext;
use Liberu\Genealogy\People\Actions\CreatePerson;
use Livewire\Livewire;

uses(RefreshDatabase::class);

it('exposes provider-neutral DNA segment analysis through the authenticated API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $kitA = ['1' => []];
    $kitB = ['1' => []];
    for ($index = 0; $index < 500; $index++) {
        $position = 1_000_000 + ($index * 50_000);
        $kitA['1'][(string) $position] = 'AG';
        $kitB['1'][(string) $position] = 'AA';
    }

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/matches/analyze', [
        'kit_a' => $kitA,
        'kit_b' => $kitB,
    ])->assertOk()
        ->assertJsonPath('data.shared_segments_count', 1)
        ->assertJsonPath('data.predicted_relationship', 'Distant Cousin');
});

it('exposes three-way DNA triangulation through the authenticated API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $segment = fn (int $start, int $end): array => [['chromosome' => '1', 'start' => $start, 'end' => $end]];

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/matches/triangulate', [
        'matches' => [
            ['id' => 'a', 'segments' => $segment(1_000_000, 30_000_000)],
            ['id' => 'b', 'segments' => $segment(5_000_000, 35_000_000)],
            ['id' => 'c', 'segments' => $segment(10_000_000, 40_000_000)],
        ],
    ])->assertOk()
        ->assertJsonPath('data.0.match_ids.0', 'a')
        ->assertJsonPath('data.0.centimorgans', 20);
});

it('validates DNA content without persisting the sensitive file', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $content = "# This data file generated by 23andMe\n".str_repeat("rs123\t1\t100\tAA\n", 100);

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/kits/validate', ['content' => $content])
        ->assertOk()
        ->assertJsonPath('data.valid', true)
        ->assertJsonPath('data.format', '23andme');
});

it('imports raw DNA encrypted at rest and removes the vault entry on kit deletion', function (): void {
    Storage::fake('private');
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->getKey());
    $content = "# This data file generated by 23andMe\n".str_repeat("rs123\t1\t100\tAA\n", 100);

    $kit = app(ImportDnaKit::class)->execute($content, ['name' => 'Encrypted import']);
    $stored = Storage::disk('private')->get($kit->file_path);

    expect($stored)->not->toBe($content)
        ->and(app(DnaFileVault::class)->read($kit->file_path))->toBe($content)
        ->and($kit->file_format)->toBe('23andme')
        ->and($kit->snp_count)->toBe(100);

    $comparisonContent = "# This data file generated by 23andMe\n";
    for ($index = 0; $index < 500; $index++) {
        $comparisonContent .= 'rs'.$index."\t1\t".(1_000_000 + ($index * 50_000))."\tAA\n";
    }
    $kitA = app(ImportDnaKit::class)->execute($comparisonContent, ['name' => 'Comparison A', 'consent_status' => 'granted']);
    $kitB = app(ImportDnaKit::class)->execute($comparisonContent, ['name' => 'Comparison B', 'consent_status' => 'granted']);
    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/matches/compare', [
        'kit_a' => $kitA->getKey(),
        'kit_b' => $kitB->getKey(),
    ])->assertOk()->assertJsonPath('data.comparison_performed', true);

    $persisted = app(TeamContext::class)->run($team->getKey(), fn (): array => app(PersistDnaComparison::class)->execute($kitA, $kitB));
    $persistedMatchCount = app(TeamContext::class)->run($team->getKey(), fn (): int => DnaMatch::query()
        ->whereIn('external_id', ['kit:'.$kitA->getKey(), 'kit:'.$kitB->getKey()])
        ->count());
    expect($persisted['persisted_match_ids'])->toHaveCount(2)
        ->and($persistedMatchCount)->toBe(2);

    app(TeamContext::class)->set($team->getKey());
    Livewire::actingAs($user)
        ->test('genealogy-dna-list')
        ->set('name', 'Livewire imported kit')
        ->set('content', $content)
        ->call('import')
        ->assertDispatched('genealogy-dna-kit-imported');
    app(TeamContext::class)->set($team->getKey());
    Livewire::actingAs($user)
        ->test('genealogy-dna-kit-comparison')
        ->set('kitA', $kitA->getKey())
        ->set('kitB', $kitB->getKey())
        ->call('compare')
        ->assertDispatched('genealogy-dna-kits-compared')
        ->assertSee('Distant Cousin');

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/kits/import', [
        'content' => $content,
        'name' => 'API encrypted import',
    ])->assertCreated()->assertJsonPath('data.attributes.has_file', true);

    app(TeamContext::class)->set($team->getKey());
    app(DeleteDnaKit::class)->execute($kit);
    Storage::disk('private')->assertMissing($kit->file_path);
});

it('does not persist a DNA match when genotype data is unreadable', function (): void {
    Storage::fake('private');
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kitA = app(CreateDnaKit::class)->execute(['name' => 'Unreadable A', 'file_path' => 'missing-a', 'consent_status' => 'granted']);
    $kitB = app(CreateDnaKit::class)->execute(['name' => 'Unreadable B', 'file_path' => 'missing-b', 'consent_status' => 'granted']);

    $result = app(PersistDnaComparison::class)->execute($kitA, $kitB);

    expect($result['comparison_performed'])->toBeFalse()
        ->and($result['skipped_reason'])->toBe('unreadable_genotype_data')
        ->and(DnaMatch::query()->count())->toBe(0);
});

it('emits a reusable event for newly persisted reciprocal DNA matches', function (): void {
    Event::fake();
    Storage::fake('private');
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $content = "# This data file generated by 23andMe\n";
    for ($index = 0; $index < 500; $index++) {
        $content .= 'rs'.$index."\t1\t".(1_000_000 + ($index * 50_000))."\tAA\n";
    }
    [$kitA, $kitB] = app(TeamContext::class)->run($team->id, fn (): array => [
        app(ImportDnaKit::class)->execute($content, ['name' => 'Event A', 'consent_status' => 'granted']),
        app(ImportDnaKit::class)->execute($content, ['name' => 'Event B', 'consent_status' => 'granted']),
    ]);

    app(TeamContext::class)->run($team->id, fn (): array => app(PersistDnaComparison::class)->execute($kitA, $kitB));
    app(TeamContext::class)->run($team->id, fn (): array => app(PersistDnaComparison::class)->execute($kitA, $kitB));

    Event::assertDispatchedTimes(DnaMatchesPersisted::class, 2);
    Event::assertDispatched(DnaMatchesPersisted::class, fn (DnaMatchesPersisted $event): bool => count($event->newMatchIds) === 2);
    Event::assertDispatched(DnaMatchesPersisted::class, fn (DnaMatchesPersisted $event): bool => $event->newMatchIds === []);
});

it('returns bounded DNA group resource envelopes through the API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);

    $this->actingAs($user)
        ->postJson('/api/v1/genealogy/dna/groups', ['name' => 'Maternal matches'])
        ->assertCreated()
        ->assertJsonPath('data.type', 'genealogy-dna-group');

    $this->actingAs($user)
        ->getJson('/api/v1/genealogy/dna/groups?page%5Bsize%5D=101')
        ->assertUnprocessable()
        ->assertJsonValidationErrors(['page.size']);
});

it('provides a tenant-scoped provider registry across domain, API, Filament, and Livewire', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->getKey());

    $provider = app(CreateDnaProvider::class)->execute(['name' => 'Family DNA', 'website' => 'https://example.test']);
    expect($provider->slug)->toBe('family-dna')
        ->and(DnaProviderResource::getPages())->toHaveKeys(['index', 'create', 'edit']);

    $kit = app(CreateDnaKit::class)->execute(['name' => 'Provider kit', 'provider_id' => $provider->getKey()]);
    expect($kit->refresh()->dnaProvider->is($provider))->toBeTrue();

    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/providers')->assertOk()
        ->assertJsonPath('data.0.type', 'genealogy-dna-provider')
        ->assertJsonPath('data.0.attributes.kits_count', 1);
    $this->actingAs($user)->patchJson('/api/v1/genealogy/dna/providers/'.$provider->getKey(), ['status' => 'inactive'])
        ->assertOk()->assertJsonPath('data.attributes.status', 'inactive');

    Livewire::actingAs($user)->test('genealogy-dna-provider-list')
        ->set('search', 'Family')
        ->assertSee('Family DNA')
        ->call('edit', (string) $provider->getKey())
        ->set('name', 'Family DNA Updated')
        ->call('save')
        ->assertDispatched('genealogy-dna-provider-saved');

    expect($provider->refresh()->name)->toBe('Family DNA Updated');
    app(TeamContext::class)->set($team->getKey());
    app(UpdateDnaProvider::class)->execute($provider, ['status' => 'active']);
    app(DeleteDnaProvider::class)->execute($provider);
    expect(DnaProvider::query()->find($provider->getKey()))->toBeNull();
});

it('rejects provider references owned by another team', function (): void {
    $owner = User::factory()->create();
    $ownerTeam = Team::factory()->create(['user_id' => $owner->id]);
    $owner->forceFill(['current_team_id' => $ownerTeam->getKey()])->save();
    app(TeamContext::class)->set($ownerTeam->getKey());
    $provider = app(CreateDnaProvider::class)->execute(['name' => 'Private provider']);

    $otherUser = User::factory()->create();
    $otherTeam = Team::factory()->create(['user_id' => $otherUser->id]);
    app(TeamContext::class)->set($otherTeam->getKey());

    expect(fn () => app(CreateDnaKit::class)->execute(['name' => 'Cross tenant kit', 'provider_id' => $provider->getKey()]))
        ->toThrow(ValidationException::class);
});

it('protects DNA kit and match references at the tenant boundary', function (): void {
    $firstUser = User::factory()->create();
    $firstTeam = Team::factory()->create(['user_id' => $firstUser->id]);
    app(TeamContext::class)->set($firstTeam->getKey());
    $person = app(CreatePerson::class)->execute(['given_name' => 'Private DNA subject']);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Private kit', 'person_id' => $person->getKey()]);

    $secondTeam = Team::factory()->create(['user_id' => User::factory()->create()->id]);
    app(TeamContext::class)->set($secondTeam->getKey());

    expect(fn () => app(CreateDnaKit::class)->execute(['name' => 'Cross-team person', 'person_id' => $person->getKey()]))
        ->toThrow(ValidationException::class, 'selected DNA person');
    expect(fn () => app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'cross-team']))
        ->toThrow(ValidationException::class, 'selected DNA kit');
});

it('rejects an oversized nested page size on DNA kit collections', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);

    $this->actingAs($user)
        ->getJson('/api/v1/genealogy/dna/kits?page%5Bsize%5D=101')
        ->assertUnprocessable()
        ->assertJsonValidationErrors(['page.size']);
});

it('returns DNA collection resources as a flat data/meta envelope', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->getKey());
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Envelope kit']);
    app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'envelope-match']);

    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/kits')->assertOk()->assertJsonPath('data.0.type', 'genealogy-dna-kit')->assertJsonPath('meta.total', 1);
    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/matches?include_private=1')->assertOk()->assertJsonPath('data.0.type', 'genealogy-dna-match')->assertJsonPath('meta.total', 1);
});

it('keeps DNA kit CRUD mutations behind tenant-safe domain actions', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Original kit']);

    $updated = app(UpdateDnaKit::class)->execute($kit, ['name' => 'Updated kit']);
    app(DeleteDnaKit::class)->execute($updated);

    expect(DnaKit::query()->withTrashed()->find($kit->getKey())->name)->toBe('Updated kit')
        ->and(DnaKit::query()->find($kit->getKey()))->toBeNull();
});

it('filters DNA matches and groups through their Livewire presentation components', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Family kit']);
    app(CreateDnaMatch::class)->execute([
        'kit_id' => $kit->id,
        'external_id' => 'match-1',
        'display_name' => 'Maternal match',
        'status' => 'active',
        'confidence' => 88,
        'is_private' => false,
    ]);
    app(CreateDnaGroup::class)->execute(['name' => 'Maternal group', 'status' => 'active']);

    Livewire::actingAs($user)
        ->test('genealogy-dna-match-list')
        ->set('search', 'Maternal')
        ->assertSee('Maternal match');

    Livewire::actingAs($user)
        ->test('genealogy-dna-match-list')
        ->set('status', 'unsupported')
        ->assertHasErrors(['status']);

    Livewire::actingAs($user)
        ->test('genealogy-dna-group-list')
        ->set('status', 'active')
        ->assertSee('Maternal group');

    Livewire::actingAs($user)
        ->test('genealogy-dna-group-list')
        ->set('status', 'unsupported')
        ->assertHasErrors(['status']);

    expect(DnaKit::query()->count())->toBe(1)
        ->and(DnaGroup::query()->count())->toBe(1);
});

it('requires authentication for DNA Livewire read surfaces', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);

    Livewire::actingAs($user)
        ->test('genealogy-dna-list')
        ->set('status', 'unsupported')
        ->assertHasErrors(['status']);

    Livewire::actingAs($user)
        ->test('genealogy-dna-provider-list')
        ->set('status', 'unsupported')
        ->assertHasErrors(['status']);

    auth()->logout();

    Livewire::test('genealogy-dna-list')->assertForbidden();
});

it('keeps DNA group and match CRUD mutations behind domain actions', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Group test kit']);
    $group = app(CreateDnaGroup::class)->execute(['name' => 'Original group']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'group-test-match']);

    $updatedGroup = app(UpdateDnaGroup::class)->execute($group, ['name' => 'Updated group']);
    $updatedMatch = app(UpdateDnaMatch::class)->execute($match, ['confidence' => 77]);
    app(DeleteDnaGroup::class)->execute($updatedGroup);
    app(DeleteDnaMatch::class)->execute($updatedMatch);

    expect(DnaGroup::query()->find($group->getKey()))->toBeNull()
        ->and(DnaMatch::query()->find($match->getKey()))->toBeNull();
});

it('validates DNA group names and statuses through domain actions', function (): void {
    $team = Team::factory()->create(['user_id' => User::factory()->create()->id]);
    app(TeamContext::class)->set($team->id);
    $group = app(CreateDnaGroup::class)->execute(['name' => 'Valid group']);

    expect($group->status)->toBe('active')
        ->and(fn () => app(UpdateDnaGroup::class)->execute($group, ['status' => 'invalid']))
        ->toThrow(ValidationException::class);
});

it('exposes DNA notes and person relationship annotations through the API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Annotation kit']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'annotation-match']);
    $person = app(CreatePerson::class)->execute(['given_name' => 'DNA', 'family_name' => 'Researcher']);

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/notes', [
        'noteable_type' => DnaMatch::class, 'noteable_id' => $match->getKey(), 'body' => 'Discuss this match with the research team.',
    ])->assertCreated()->assertJsonPath('data.type', 'genealogy-dna-note');
    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/relationships', [
        'match_id' => $match->getKey(), 'person_id' => $person->getKey(), 'relationship_type' => 'possible_parent', 'confidence' => 72,
    ])->assertCreated()->assertJsonPath('data.type', 'genealogy-dna-relationship');
    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/relationships?match_id='.$match->getKey())->assertOk()->assertJsonCount(1, 'data');

    Livewire::actingAs($user)->test('genealogy-dna-annotation-list', ['matchId' => $match->getKey()])->assertSee('Discuss this match');
});

it('keeps DNA annotation deletion behind tenant-safe actions', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Deletion kit']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'deletion-match']);
    $person = app(CreatePerson::class)->execute(['given_name' => 'Annotation']);
    $note = app(CreateDnaNote::class)->execute(['noteable_type' => DnaMatch::class, 'noteable_id' => $match->getKey(), 'body' => 'Temporary note']);
    $relationship = app(CreateDnaRelationship::class)->execute(['match_id' => $match->getKey(), 'person_id' => $person->getKey(), 'relationship_type' => 'possible_parent']);

    app(DeleteDnaNote::class)->execute($note);
    app(DeleteDnaRelationship::class)->execute($relationship);

    expect(DnaNote::query()->find($note->getKey()))->toBeNull()
        ->and(DnaRelationship::query()->find($relationship->getKey()))->toBeNull();
});

it('exposes tenant-safe segment lifecycle and consent history across presentation surfaces', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->getKey());
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Lifecycle kit']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'lifecycle-match']);
    $segment = app(CreateDnaSegment::class)->execute(['match_id' => $match->getKey(), 'chromosome' => 1, 'start_position' => 100, 'end_position' => 200]);

    app(UpdateDnaSegment::class)->execute($segment, ['end_position' => 250]);
    $consent = app(GrantDnaConsent::class)->execute($kit, 'matching', '2026-01');

    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/matches/'.$match->getKey().'/segments')
        ->assertOk()->assertJsonPath('data.0.attributes.end_position', 250);
    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/kits/'.$kit->getKey().'/consents')
        ->assertOk()->assertJsonPath('data.0.attributes.scope', 'matching');

    Livewire::actingAs($user)->test('genealogy-dna-segment-list', ['matchId' => $match->getKey()])->assertSee('Chromosome 1');
    Livewire::actingAs($user)->test('genealogy-dna-consent-list', ['kitId' => $kit->getKey()])->assertSee('matching');

    app(TeamContext::class)->set($team->getKey());
    app(DeleteDnaSegment::class)->execute($segment->refresh());

    expect(DnaSegment::query()->find($segment->getKey()))->toBeNull()
        ->and($consent->fresh()->granted)->toBeTrue();
});

it('rejects DNA consent mutations for kits outside the active team', function (): void {
    $owner = User::factory()->create();
    $kitTeam = Team::factory()->create(['user_id' => $owner->id]);
    app(TeamContext::class)->set($kitTeam->getKey());
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Private consent kit']);

    $otherTeam = Team::factory()->create(['user_id' => User::factory()->create()->id]);
    app(TeamContext::class)->set($otherTeam->getKey());

    expect(fn () => app(GrantDnaConsent::class)->execute($kit, 'matching'))
        ->toThrow(InvalidArgumentException::class)
        ->and(fn () => app(RevokeDnaKit::class)->execute($kit, 'No longer participating'))
        ->toThrow(InvalidArgumentException::class)
        ->and(DnaConsent::withoutGlobalScopes()->where('kit_id', $kit->getKey())->count())->toBe(0)
        ->and($kit->refresh()->consent_status)->toBe('pending');
});
