<?php

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Liberu\Foundation\Organizations\Models\Team;
use Liberu\Genealogy\Dna\Actions\CreateDnaGroup;
use Liberu\Genealogy\Dna\Actions\CreateDnaKit;
use Liberu\Genealogy\Dna\Actions\CreateDnaMatch;
use Liberu\Genealogy\Dna\Actions\CreateDnaNote;
use Liberu\Genealogy\Dna\Actions\CreateDnaRelationship;
use Liberu\Genealogy\Dna\Actions\DeleteDnaGroup;
use Liberu\Genealogy\Dna\Actions\DeleteDnaKit;
use Liberu\Genealogy\Dna\Actions\DeleteDnaMatch;
use Liberu\Genealogy\Dna\Actions\DeleteDnaNote;
use Liberu\Genealogy\Dna\Actions\DeleteDnaRelationship;
use Liberu\Genealogy\Dna\Actions\UpdateDnaGroup;
use Liberu\Genealogy\Dna\Actions\UpdateDnaKit;
use Liberu\Genealogy\Dna\Actions\UpdateDnaMatch;
use Liberu\Genealogy\Dna\Models\DnaGroup;
use Liberu\Genealogy\Dna\Models\DnaKit;
use Liberu\Genealogy\Dna\Models\DnaMatch;
use Liberu\Genealogy\Dna\Models\DnaNote;
use Liberu\Genealogy\Dna\Models\DnaRelationship;
use Liberu\Genealogy\GenealogyCore\TeamContext;
use Liberu\Genealogy\People\Actions\CreatePerson;
use Livewire\Livewire;

uses(RefreshDatabase::class);

it('exposes provider-neutral DNA segment analysis through the authenticated API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $kitA = ['1' => []];
    $kitB = ['1' => []];
    for ($index = 0; $index < 500; $index++) {
        $position = 1_000_000 + ($index * 50_000);
        $kitA['1'][(string) $position] = 'AG';
        $kitB['1'][(string) $position] = 'AA';
    }

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/matches/analyze', [
        'kit_a' => $kitA,
        'kit_b' => $kitB,
    ])->assertOk()
        ->assertJsonPath('data.shared_segments_count', 1)
        ->assertJsonPath('data.predicted_relationship', 'Distant Cousin');
});

it('exposes three-way DNA triangulation through the authenticated API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $segment = fn (int $start, int $end): array => [['chromosome' => '1', 'start' => $start, 'end' => $end]];

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/matches/triangulate', [
        'matches' => [
            ['id' => 'a', 'segments' => $segment(1_000_000, 30_000_000)],
            ['id' => 'b', 'segments' => $segment(5_000_000, 35_000_000)],
            ['id' => 'c', 'segments' => $segment(10_000_000, 40_000_000)],
        ],
    ])->assertOk()
        ->assertJsonPath('data.0.match_ids.0', 'a')
        ->assertJsonPath('data.0.centimorgans', 20);
});

it('validates DNA content without persisting the sensitive file', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $content = "# This data file generated by 23andMe\n".str_repeat("rs123\t1\t100\tAA\n", 100);

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/kits/validate', ['content' => $content])
        ->assertOk()
        ->assertJsonPath('data.valid', true)
        ->assertJsonPath('data.format', '23andme');
});

it('returns bounded DNA group resource envelopes through the API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);

    $this->actingAs($user)
        ->postJson('/api/v1/genealogy/dna/groups', ['name' => 'Maternal matches'])
        ->assertCreated()
        ->assertJsonPath('data.type', 'genealogy-dna-group');

    $this->actingAs($user)
        ->getJson('/api/v1/genealogy/dna/groups?page%5Bsize%5D=101')
        ->assertUnprocessable()
        ->assertJsonValidationErrors(['page.size']);
});

it('rejects an oversized nested page size on DNA kit collections', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);

    $this->actingAs($user)
        ->getJson('/api/v1/genealogy/dna/kits?page%5Bsize%5D=101')
        ->assertUnprocessable()
        ->assertJsonValidationErrors(['page.size']);
});

it('keeps DNA kit CRUD mutations behind tenant-safe domain actions', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Original kit']);

    $updated = app(UpdateDnaKit::class)->execute($kit, ['name' => 'Updated kit']);
    app(DeleteDnaKit::class)->execute($updated);

    expect(DnaKit::query()->withTrashed()->find($kit->getKey())->name)->toBe('Updated kit')
        ->and(DnaKit::query()->find($kit->getKey()))->toBeNull();
});

it('filters DNA matches and groups through their Livewire presentation components', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Family kit']);
    app(CreateDnaMatch::class)->execute([
        'kit_id' => $kit->id,
        'external_id' => 'match-1',
        'display_name' => 'Maternal match',
        'status' => 'active',
        'confidence' => 88,
        'is_private' => false,
    ]);
    app(CreateDnaGroup::class)->execute(['name' => 'Maternal group', 'status' => 'active']);

    Livewire::actingAs($user)
        ->test('genealogy-dna-match-list')
        ->set('search', 'Maternal')
        ->assertSee('Maternal match');

    Livewire::actingAs($user)
        ->test('genealogy-dna-group-list')
        ->set('status', 'active')
        ->assertSee('Maternal group');

    expect(DnaKit::query()->count())->toBe(1)
        ->and(DnaGroup::query()->count())->toBe(1);
});

it('keeps DNA group and match CRUD mutations behind domain actions', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Group test kit']);
    $group = app(CreateDnaGroup::class)->execute(['name' => 'Original group']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'group-test-match']);

    $updatedGroup = app(UpdateDnaGroup::class)->execute($group, ['name' => 'Updated group']);
    $updatedMatch = app(UpdateDnaMatch::class)->execute($match, ['confidence' => 77]);
    app(DeleteDnaGroup::class)->execute($updatedGroup);
    app(DeleteDnaMatch::class)->execute($updatedMatch);

    expect(DnaGroup::query()->find($group->getKey()))->toBeNull()
        ->and(DnaMatch::query()->find($match->getKey()))->toBeNull();
});

it('exposes DNA notes and person relationship annotations through the API', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    $user->forceFill(['current_team_id' => $team->getKey()])->save();
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Annotation kit']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'annotation-match']);
    $person = app(CreatePerson::class)->execute(['given_name' => 'DNA', 'family_name' => 'Researcher']);

    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/notes', [
        'noteable_type' => DnaMatch::class, 'noteable_id' => $match->getKey(), 'body' => 'Discuss this match with the research team.',
    ])->assertCreated()->assertJsonPath('data.type', 'genealogy-dna-note');
    $this->actingAs($user)->postJson('/api/v1/genealogy/dna/relationships', [
        'match_id' => $match->getKey(), 'person_id' => $person->getKey(), 'relationship_type' => 'possible_parent', 'confidence' => 72,
    ])->assertCreated()->assertJsonPath('data.type', 'genealogy-dna-relationship');
    $this->actingAs($user)->getJson('/api/v1/genealogy/dna/relationships?match_id='.$match->getKey())->assertOk()->assertJsonCount(1, 'data');

    Livewire::actingAs($user)->test('genealogy-dna-annotation-list', ['matchId' => $match->getKey()])->assertSee('Discuss this match');
});

it('keeps DNA annotation deletion behind tenant-safe actions', function (): void {
    $user = User::factory()->create();
    $team = Team::factory()->create(['user_id' => $user->id]);
    app(TeamContext::class)->set($team->id);
    $kit = app(CreateDnaKit::class)->execute(['name' => 'Deletion kit']);
    $match = app(CreateDnaMatch::class)->execute(['kit_id' => $kit->getKey(), 'external_id' => 'deletion-match']);
    $person = app(CreatePerson::class)->execute(['given_name' => 'Annotation']);
    $note = app(CreateDnaNote::class)->execute(['noteable_type' => DnaMatch::class, 'noteable_id' => $match->getKey(), 'body' => 'Temporary note']);
    $relationship = app(CreateDnaRelationship::class)->execute(['match_id' => $match->getKey(), 'person_id' => $person->getKey(), 'relationship_type' => 'possible_parent']);

    app(DeleteDnaNote::class)->execute($note);
    app(DeleteDnaRelationship::class)->execute($relationship);

    expect(DnaNote::query()->find($note->getKey()))->toBeNull()
        ->and(DnaRelationship::query()->find($relationship->getKey()))->toBeNull();
});
