<?php

declare(strict_types=1);

use Illuminate\Database\Capsule\Manager as Capsule;
use Liberu\Genealogy\Dna\Actions\CreateDnaKit;
use Liberu\Genealogy\Dna\Models\DnaKit;
use Liberu\Genealogy\Dna\Services\AnalyzeDnaMatch;
use Liberu\Genealogy\Dna\Services\DnaFileValidator;
use Liberu\Genealogy\Dna\Services\RelationshipEstimator;
use Liberu\Genealogy\Dna\Services\SegmentMatcher;
use Liberu\Genealogy\Dna\Services\TriangulateDna;

it('creates and hydrates its aggregate through the domain action', function (): void {
    $database = new Capsule();
    $database->addConnection(['driver' => 'sqlite', 'database' => ':memory:']);
    $database->setAsGlobal();
    $database->bootEloquent();
    $database->schema()->create('genealogy_dna_kits', function ($table): void {
        $table->uuid('id')->primary();
        $table->string('name');
        $table->string('status');
        $table->json('metadata')->nullable();
        $table->timestamps();
        $table->softDeletes();
    });

    $record = (new CreateDnaKit())->execute([
        'name' => 'Sample record',
        'status' => 'active',
        'metadata' => ['source' => 'archive'],
    ]);

    expect($record)->toBeInstanceOf(DnaKit::class)
        ->and($record->exists)->toBeTrue()
        ->and($record->name)->toBe('Sample record')
        ->and($record->status)->toBe('active');
});

it('matches autosomal segments and estimates a relationship without a provider SDK', function (): void {
    $kitA = ['1' => []];
    $kitB = ['1' => []];
    for ($index = 0; $index < SegmentMatcher::MIN_SNPS; $index++) {
        $position = 1_000_000 + ($index * 50_000);
        $kitA['1'][$position] = 'AG';
        $kitB['1'][$position] = 'AA';
    }

    $result = (new AnalyzeDnaMatch(new SegmentMatcher(), new RelationshipEstimator()))->analyze($kitA, $kitB);

    expect($result['shared_segments_count'])->toBe(1)
        ->and($result['shared_segments'][0]['snps'])->toBe(SegmentMatcher::MIN_SNPS)
        ->and($result['total_shared_cm'])->toBeGreaterThanOrEqual(7.0)
        ->and($result['predicted_relationship'])->toBe('Distant Cousin')
        ->and(RelationshipEstimator::labels())->toContain('Parent/Child');
});

it('finds three-way overlapping DNA segments above the shared cM threshold', function (): void {
    $matches = [
        ['id' => 'a', 'segments' => [['chromosome' => '1', 'start' => 1_000_000, 'end' => 30_000_000]]],
        ['id' => 'b', 'segments' => [['chromosome' => '1', 'start' => 5_000_000, 'end' => 35_000_000]]],
        ['id' => 'c', 'segments' => [['chromosome' => '1', 'start' => 10_000_000, 'end' => 40_000_000]]],
    ];

    $groups = (new TriangulateDna())->execute($matches);

    expect($groups)->toHaveCount(1)
        ->and($groups[0]['match_ids'])->toBe(['a', 'b', 'c'])
        ->and($groups[0]['centimorgans'])->toBe(20.0);
});

it('detects supported DNA file headers and rejects unsafe input sizes', function (): void {
    $validator = new DnaFileValidator();
    $content = "# This data file generated by 23andMe\n".str_repeat("rs123\t1\t100\tAA\n", 100);

    expect($validator->validate($content)['format'])->toBe('23andme')
        ->and($validator->validate($content)['valid'])->toBeTrue()
        ->and($validator->validate('too small')['error'])->toContain('too small')
        ->and($validator->detectFormat('unknown header'))->toBeNull();
});
